apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-pico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefly-pico
  template:
    metadata:
      labels:
        app: firefly-pico
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            - sh
            - -c
            - chown -R 33:33 /var/www/html/bootstrap/cache
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: "/var/www/html/database/data"
              name: firefly-pico-data
      containers:
        - name: firefly-pico
          image: cioraneanu/firefly-pico:1.10.0
          env:
            - name: FIREFLY_URL
              value: "http://ffly.ctimms.net"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/var/www/html/database/data"
              name: firefly-pico-data
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 82
            fsGroup: 82

      volumes:
        - name: firefly-pico-data
          persistentVolumeClaim:
            claimName: firefly-pico-data-pvc
