# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: firefly-pico
spec:
  selector:
    app: firefly-pico
  ports:
    - port: 80
  type: ClusterIP
