apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.36.0
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/data"
              name: vaultwarden-data
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: vaultwarden-data
          persistentVolumeClaim:
            claimName: vaultwarden-data-pvc
