apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:BUllH0lfy/ar8yEarFs0gk1/L0seErmh3NiRzwZ3uqEoR4ezJvggs8yJ39U9i0kL7qdWsf0bRsvBkGvqOLYtlpZgoi8el+Afau/QykN5tv9dzLBHbi6Qtsu2LRpf0PD+FjYvxVsIjCGQ66aE5SIBMxP2JAGA7nNZIIBGNKD/RIZTBL5H1dk5RCuywiBzxwn15hKvhc/kh8H58tg7MMQYx6B3ipS90xU9wgAMkz5TILIdC9RogdY3CZATaI5634fcA1V/UUfA8BMKQOfDUzfL5Z+TCDPupHPvNWagG8axlBUYfbuADuszcyEYT3M=,iv:vkFK8zNMvsSYLosW5phpdn44RAndyOtlD99rXheIC7s=,tag:d3/4o6AekPyumhTDnIQtVA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxS25SWVg2cVpISEdpZWFM
            SXRkSkxIVEhWNDhiV0Q2UCtkdm85cGR1Q1ZFCnFJa1FJdzRoWTkrUHNOVFBpeTk4
            MCt0TE9QL2lrWmduNXdQMlBvcmlVdWcKLS0tIFNnMHY2bTBzWGttb0sxOGtYeGdv
            eWYrZzNPTGQvY1RnWXVFUHZNeS9POVEKLZ+lVX5P2xwcc2WJUCkZa1fVSS2wa5mz
            NU+FkrNWJtsfcsIS3kICrscJ1iDO9oE55dtTeJE8b6msjK5D0L9rNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15rwallvhy5achljpf7a2xxh4fqwc3m5wuyutdg7nu3e245upq3zsnsh4tn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T16:13:15Z"
    mac: ENC[AES256_GCM,data:d9Ef/4R8djIr6qM0cB5j84pG/an+7fyNoqWhK2Z9q2ewqIZeq44UmxUsv2TwprqT6BCaz/EVdZnkbzOB0p9G9xo3HRw3FxRLtHQTzg65TSLU734+D7Gdu60R+qcEEarYZ4dd7KlDNPtSdr3C1XsAbUhFTlwRQBNg4EAvjd5nBBk=,iv:w1H/VbzJpYJHCGnZlY3Kls50hpgaogyY9OCEspbI3tU=,tag:Bgae5T2srWq5s8nU7IoKmA==,type:str]
    version: 3.13.1
