apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:zAYGDnYh5S2lrCQRGLRu9JVDvLoNhG9x1hl1awUGZlex2vCqyMtt8AMqIcRQwVvDSyxlBZBpqaVu9MVmlh8fq6EpMajdhfYkvz9194dkq4on5cEIi7SISjQuJ5NOnY2qXpggaC2fCDOKQ5jaaO5UI9fmAxpWhrLIehDHStBmrFwrIWiP79tO+ctwpXhj0bmd/JuFIW12vd3qOuy73t+iOXz0Qo6jeZ+spZ39kQAwlKjVbgO1jPyZ5FBDFC21Q1TYj+CqprJR6RsJuerKb+r8KFjnnmZbSm8NfxFp1gnR9LrO7GJToUtj+1tytpA=,iv:umlq1eL4+vum8RVRUmXK6VCZm9l3y85emGfUzwgUO/Y=,tag:hjWbT5rNNeJbvl/fkqzjSg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6K0QwcEdKUGxWZzc4cyto
            eW1pNE9SeXdUNmtudDJLS3RBakhBb3V4cHowCkNuZ0l5anY2aTk1YnpqSG4zUzMz
            QW1VckRsRlRSNTMxNVVMVEFrd29Eb0UKLS0tIEFLWE5xemFmcXBhYXR2SVAweXVZ
            NzUzdVdNdnVrVUwrVEdYeXBwQ2pKN1kK3FU1FnYvi0YNL4pw5mbtbEyI++pjwtyu
            IRvLha58XUC1hAcmIzxmR4ITXsT98IUYZKzEcAxQ7gIQOrLHPjuYUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15rwallvhy5achljpf7a2xxh4fqwc3m5wuyutdg7nu3e245upq3zsnsh4tn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T16:41:22Z"
    mac: ENC[AES256_GCM,data:CcNW9Mxo8DsT+9jpVLiIK9pzMRybIjUghvB7S+6lV8kgstOfJCfEQatjEACH3lSd7m1DNlshUUrgkapZ3cdkJdS6IbOQ8jT5w12QRZouNvZi+jlGl0fnls9NDR+VKheQ80kJxRSATGCY0mLf+MiYE+lxziLG+zFAW0rrFnrjRSU=,iv:Ksplya7y9q0jVjvv3W22K+ElcdT5LAAUshEARIXg4Og=,tag:FtQfzKdgnMLb5n0qS7d0IQ==,type:str]
    version: 3.13.1
