apiVersion: batch/v1
kind: CronJob
metadata:
  name: firefly-importer-script
spec:
  schedule: "2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            fsGroup: 999
          containers:
            - name: firefly-importer
              image: ghcr.io/ctimmsy/firefly-importer:sha256-d1f8f5193e4f2466aebb6050c34582fe1640b3b5741fd053c04cc9a7873db22d
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: "/data"
                  name: firefly-importer-script-data
          volumes:
            - name: firefly-importer-script-data
              persistentVolumeClaim:
              claimName: firefly-importer-script-db-storage-claim

          restartPolicy: OnFailure
