apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-importer-script-db-storage-claim
  namespace: firefly-importer-script
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
