apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly
  namespace: firefly
spec:
  interval: 30m
  chart:
    spec:
      chart: firefly-iii-stack
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: firefly
        namespace: firefly
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    firefly-db:
      configs:
        TZ: "Europe/London"
      accessModes:
        - ReadWriteOnce

    firefly-iii:
      config:
        env:
          DEFAULT_LANGUAGE: "en_GB"
          TZ: "Europe/London"
