apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-firefly-db-storage-claim
  namespace: firefly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
