apiVersion: v1
data:
    password: ENC[AES256_GCM,data:IzEURN7einRX2LFWdE3IEpnzVgw=,iv:Mkdkn3l9rNdaHxtnvq/vYS3UKni0YDIagJfmnbknyIM=,tag:HagsFL2+tqspr9z45x0yBQ==,type:str]
    username: ENC[AES256_GCM,data:fsVCD5XZ16E=,iv:JZoEBb+7Qceoke7YSgTrk9E7BxTT4k6lTqpLWsh4MPc=,tag:wrMfCb7AEdHnb1V7plVBDw==,type:str]
kind: Secret
metadata:
    name: ld-admin-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZEtETExZNHdqMWUzSnRS
            TGtrQW1wSUFNZGR1djNPSzhxS25xK1BrS2dZCmQ3QjExV3pBT0J6NTQxbkRYQURL
            OEZmdFExMW04UjlwdVovRjBrajJjalUKLS0tIHpaRlNyV2NyZjZBZldMaG5ZRkNj
            bVkvajhBLzVidTMxSHZUdHdUUlFRSWMKPptvjyBkekMtE56PKLTbPFy4rDW25aGX
            zg8b0T/g2VaY8fOpYCSHtCo/T/wGgOnmSB1BHMba52NzYiNUR1bKug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15rwallvhy5achljpf7a2xxh4fqwc3m5wuyutdg7nu3e245upq3zsnsh4tn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T17:36:11Z"
    mac: ENC[AES256_GCM,data:octL2u2gJwVhuesWazP6DIUGJLPpeSLGUdzbQPKmeSq7vM0Av/zdwgJ0RkjBQkyzeUOkP4ixkmnvjc3CSf/77tTUmfepIhBu4n4PwRXM9qrcBtdEgL5UVPf2srNGPFjeRfLTmgLoei1O6iSkOUZeL64aciz5guwB3OEFNa0VQBY=,iv:cs1pDlIqsENZzIB0weV4xU/1se38A/WHS441Fn44z+U=,tag:FOxj8Za1+pvQyT5i4VMuNw==,type:str]
    version: 3.13.1
