apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:xIX1laEf2l0=,iv:B3o335cRjg4GkjP2XSIva8J/LD7NR/iYKOItSNnmFM8=,tag:PlL5NqXjqhqJwO9KebBqXw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:JI3O2HQtsGInTJc2EWajENYUcHM=,iv:GqzT6ifos0bJMCvaiUhFrX39Nfa7WSTbmY5ZEXPLi78=,tag:FNR6ooe65J74bifWmOeaJA==,type:str]
kind: Secret
metadata:
    name: ld-credentials-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VHdtZDZ5eGQ3c3Z0a1N1
            UVp2WFZld3JKUC9vMkh4VEVrUGRjTUlpT213CklpUFRBRTRwQm9EeG5GM3FLSXlv
            NmFzVDVRVHR3dGZva29WdlVNWENobU0KLS0tIFNmVjBvcytiY3dxQ2owYm4zaFNH
            aHdybXRJLy81VGJHUW9ZRkZIbEtpOXMKXHIu1z6JbHVHZqQNrbLmt+EjxFoR5dDX
            y2t9nZ1hlljQu8HOis2Bpx/7VfqIV0h4WcIZYe3Q7HeemBc+6y7Prw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15rwallvhy5achljpf7a2xxh4fqwc3m5wuyutdg7nu3e245upq3zsnsh4tn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T21:10:19Z"
    mac: ENC[AES256_GCM,data:tt9GjBrVCZVaV4kKgw++ezaMjgzF0RR5LNNGOeitt+kz8jEqW24GATrHH2Bty3W+o64FHqxryAljmDC6WbOiJis3VhrzMVUBChKbdCtGQB+xLARcyKRSE95cjuJ5qMJmil5wcliHDAdYMb4lsT/Np4WvezAm2hKqVnBFb9I5UGM=,iv:dd6NvYLttxtU6vzKgb293pewwcMkuX4jc2OnLTFQpoA=,tag:upGF/AtqDwOEaezm5OtA4Q==,type:str]
    version: 3.13.1
