apiVersion: v1
data:
    password: ENC[AES256_GCM,data:3oE9EqUgsVw=,iv:JYtDtycRNNvqy3IChPJu8Yrjc6D6+HRqd9KjevU+ndM=,tag:Dctyri44m5Jz2nWyBNG/9w==,type:str]
    user: ENC[AES256_GCM,data:u4f/dgz7Ygg=,iv:nxWXGSojq+n11Gv7xbzTdvGwbsoCYlQAU1C6vCEj9Ig=,tag:sQ3Y15rs9WU5YtpF/9DoKg==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDM2cwb1FFaFFDY0M5TWRW
            UTdrbUtxNWVlZFg1NkNjUjBZMzM0VWRjUTFrCjJ4SFRFLytOMjVHaldjOVlWLzRa
            MFA4ZTcxMjg5eURUbmxWanNidG9QTlUKLS0tIHJpRUhBamRmTElXUFQwNFNYY1lm
            anU5am9MQW1QaHVTd2prTlBuTERrbVkK5yXud4S8IE+riL6nrqxqsSf4emE/5xge
            1lfCHfO7o7TfFwhJww5y7fNtzZljxvpgm7um0NRuUcw3V5vHTGQ7dQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15rwallvhy5achljpf7a2xxh4fqwc3m5wuyutdg7nu3e245upq3zsnsh4tn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T14:58:03Z"
    mac: ENC[AES256_GCM,data:KDFNFuz3YG9FJKyGB0doquu60hf8OrMKzXuOOCD2bYDMe5MZgOurFoSjPWEQtL0ZYk/Vt4S87DBAMZbIKhiWGuQhvle36b59UIoEvfPpV2IaxEIYfanZsTcUYKazAZL2e1oQNuKEKqB8uxnR7yXThoWB4iFSGOHrT6DIh3UU3uc=,iv:sI/k8OH60SxvqijTmXGgod5Ky0fY9Kfrc2SK45scbGc=,tag:P1dvkk90VnYu+JnVJOkFYA==,type:str]
    version: 3.13.1
