apiVersion: v1
data:
    cda4f613-1d1e-4a0a-814b-59136d0b8617.json: ENC[AES256_GCM,data:uXmBo4raoQs9zpErClC04yIyaKCpchNh1Awi7TzmUVDKi87X6Vlx1RQOueh1kRxru18AaqsT+rjHgVXQ1dRg1EVxlHG98NfQgJQ10MTLP9OxAu+iK9Odcf9ANLnr4Y2L02R+BYB6ZlqI2Jwr8UTcTofE/cG18dqmRC7Mj9rCDXtNmN0kUuWuk/IRnQUz5xq7mqzu7Cjsl2/5JQpHMMAZyMaFcEqqBQsOv8yMARRfdFTmsO3/M/EeajfyOfs0selEdhR4cyHjVx5T8Zch13BeEdbatY8Ie/3uJJsWvJTPYi9MGMS4AaEbYiczUN8=,iv:iFUugTrxK1k0tdo9pzfz3CFFLvoA2Lf723SgWf1XH7o=,tag:Q13ITqWbHTyua46THcDgCg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMazdOczhTQnpxVlJpS2dL
            VEV0QXppdllrNmFKMi9HVExVdElQMHZ6MDJNCnE1M2Jnblg5TUUyckY5ZlVSc0tk
            bU13R1Zsb2pJbjhsR3pNTWdBYU9yV28KLS0tIGlTRU44aW5qQnZFNkhYSHYvWUZX
            S1NrZHZhRjhnZXVwUEFseFlrZWNmcWMKDCbkJrK/tSn+US08ST8Uj8+7jlhQ0yhY
            rwYf0V9YbsUOYL8jJw9+tJkqbyTjigVtXxA/zadaUu/obfZ6B8aRHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15rwallvhy5achljpf7a2xxh4fqwc3m5wuyutdg7nu3e245upq3zsnsh4tn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T16:19:35Z"
    mac: ENC[AES256_GCM,data:5v2n79Vzn/pxtoZy4SDnJ8L59vgY8aJBnNiM08wN9+z83b32QyGhmB5LC8XIsbKHLvJJFXtkQIwoPOk2lvO7Tt+lTZmEuqBsOvS2PUgXlUQyYS6GdOrka7uVPUk0LKTDvMURinE9QPSml20EmbdJFmlGogZ6yaIr0fItNFxtLJE=,iv:jiayQ4XkzFxy/p+KkrjAE981zRD0vatFtNdZ1xAuYFk=,tag:QM+UT4fOw6225rGVsZicDg==,type:str]
    version: 3.13.1
