apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:OexU19ZwMGBidruOEMe3CR/Dx0wzXDhwMcYaaPTmLLy2VpgxuGwd2vM7jHU8ORWxQIFNYowuyecs9qACE7/TYGa8TwfyfMwYsmMbr3hpHzB+WsTuTJ+5+NxO+PE3EhR9OuuU78Cv+UmRcQXzRgoFMe0bbgnuour+WwPw+WEljLSzWtj+cjYQozp+ZjhDCXgntstAjr3hA4aqY/3RLIJYR9GCcBVn7nOh5ugNObZVnDbLy5EK16TL7u1TesfT2CHCfzsuTiJJeSQN7VYzj3TMX41GDjGPnhnXikTkrnAvS60UaNWWohtfOa6t5IQ=,iv:YeguBb7xTjMApDOvMINi654uiHD1yD9zPCeGM6GIrmE=,tag:EcGmHkWxA2UX/HpcWzaxnA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbmw2d3pqWTQ3TnNGUnBo
            S1R1SmpjUHgrSjA2eUNzNjZsSndXZ25IWDNVCjVlOEVBWVJWUisxRG1Rd1RPbis1
            ZnMrNFdIalAvRzlZMkNXclBjZzFCYjgKLS0tIE9VcE5zZFNzYk9oNG1ENlRMOHp0
            TTgwaE8yREZvWExrQTlCbEY1RkhmRTQKCw0CmThbidfOCZfl06EzEMF/0CvDdGfw
            nSXNiv95wnIxn3BA8UaOUix5HvITZK7xSTJ+B0k3EdyazMZR3bOnkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15rwallvhy5achljpf7a2xxh4fqwc3m5wuyutdg7nu3e245upq3zsnsh4tn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T16:53:12Z"
    mac: ENC[AES256_GCM,data:htz0LKOf9BdMcRSCKaAIcemNKSRemThpweFaYUKRASBRrX6nMuK4wGAQot3420sxpw1QQUAjvmytUn0+NkMnH5Y5Wwe+7YQn91oMuXIwE92Xt9Do7or++wU0OUG7QLe8ItKXb/oLdebKx0T+cK5GfIzTYnMRmndbHiTAmFzRMe8=,iv:TXdHAamiYyPHmC0kZG+X+pcrfCXXdB/tLw3LHnPgtUw=,tag:WcCZcfvc4Vs4iczaLj7yUQ==,type:str]
    version: 3.13.1
