apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre
  template:
    metadata:
      labels:
        app: calibre
    spec:
      containers:
        - name: calibre
          image: linuxserver/calibre:9.11.0
          envFrom:
            - configMapRef:
                name: calibre-configmap
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/config"
              name: calibre-config
          securityContext:
            allowPrivilegeEscalation: false

        - name: calibre-web
          image: linuxserver/calibre-web:0.6.26
          envFrom:
            - configMapRef:
                name: calibre-web-configmap
          ports:
            - containerPort: 8083
          volumeMounts:
            - mountPath: "/books"
              subPath: "Calibre Library"
              name: calibre-config
            - mountPath: "/config"
              name: calibre-web-config
          securityContext:
            allowPrivilegeEscalation: false

      volumes:
        - name: calibre-config
          persistentVolumeClaim:
            claimName: calibre-storage-claim
        - name: calibre-web-config
          persistentVolumeClaim:
            claimName: calibre-web-storage-claim
