apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-storage-claim
  namespace: calibre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-storage-claim
  namespace: calibre
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
